services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=eneslab
